version: '2'
services:
  database:
    env_file:
    - ./.env
    build: mongodb
    ports:
    - 27097:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
